// Code generated by go-swagger; DO NOT EDIT.

package books

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/janPhil/bookstore/cmd/models"
)

// AllBooksReader is a Reader for the AllBooks structure.
type AllBooksReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AllBooksReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAllBooksOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAllBooksOK creates a AllBooksOK with default headers values
func NewAllBooksOK() *AllBooksOK {
	return &AllBooksOK{}
}

/*AllBooksOK handles this case with default header values.

List of books
*/
type AllBooksOK struct {
	Payload []*models.Book
}

func (o *AllBooksOK) Error() string {
	return fmt.Sprintf("[GET /books][%d] allBooksOK  %+v", 200, o.Payload)
}

func (o *AllBooksOK) GetPayload() []*models.Book {
	return o.Payload
}

func (o *AllBooksOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
