// Code generated by go-swagger; DO NOT EDIT.

package books

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new books API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for books API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	AllBooks(params *AllBooksParams) (*AllBooksOK, error)

	Book(params *BookParams) (*BookOK, error)

	DeleteBook(params *DeleteBookParams) (*DeleteBookCreated, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  AllBooks Return a list of books from the database
*/
func (a *Client) AllBooks(params *AllBooksParams) (*AllBooksOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAllBooksParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "AllBooks",
		Method:             "GET",
		PathPattern:        "/books",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &AllBooksReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*AllBooksOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for AllBooks: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  Book Returns a single book from the database
*/
func (a *Client) Book(params *BookParams) (*BookOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewBookParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "Book",
		Method:             "GET",
		PathPattern:        "/books/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &BookReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*BookOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Book: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  DeleteBook Delete a book by a given ID
*/
func (a *Client) DeleteBook(params *DeleteBookParams) (*DeleteBookCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteBookParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "DeleteBook",
		Method:             "DELETE",
		PathPattern:        "/books/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteBookReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteBookCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DeleteBook: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
